### ISSUE TITLE
Unable to automate login to Daz3d shop?

### ISSUE THREAD

**Issue by bschollnick** [jenterkin/selenium-page-elements#11]
I was looking to use this for a scrapper for the items I've purchased from Daz3d...  

But I am getting a weird error (and I've used page elements without an issue with a different web site).

```
Traceback (most recent call last):
  File "daz_test.py", line 231, in <module>
    test.login("benjamin@example.com", "password") # password changed to protect the innocent
  File "daz_test.py", line 157, in login
    self.username = username
  File "C:\Users\bschollnick\python3\validation\lib\site-packages\page_elements\input.py", line 12, in __set__
    self.element.clear()
  File "C:\Users\bschollnick\python3\validation\lib\site-packages\selenium\webdriver\remote\webelement.py", line 95, in clear

    self._execute(Command.CLEAR_ELEMENT)
  File "C:\Users\bschollnick\python3\validation\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _exe
cute
    return self._parent.execute(command, params)
  File "C:\Users\bschollnick\python3\validation\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execu
te
    self.error_handler.check_response(response)
  File "C:\Users\bschollnick\python3\validation\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in ch
eck_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidElementStateException: Message: invalid element state: Element is not currently interactabl
e and may not be manipulated
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64)
```
The URL is login_url = r"https://www.daz3d.com/customer/account/login/"

I've tried addressing the elements on the page By.NAME, By.XPATH, By.ID, and the results are the same.  The elements are right there on the page.  

Is there something I'm missing?
class login2:
    username = InputField(By.NAME, 'login[username]')
    password = InputField(By.NAME, 'login[password]')
    login_button = Element(By.LINK_TEXT, 'send')

    def login(self, username, password):
        """
            Operate the Login web page to Locker
            
            inputs -
                     username - string
                     password - string

            returns - None
        """
        try:
            self.username = username
            self.password = password
            self.login_button.click()
        except NoSuchElementException:
            print ("Unable to login, unable to find username / password field.")

Any advice and suggestions would be welcome...

**Comment by jenterkin** [comment]
Oof, missed this by a few years. I honestly didn't think anyone would end up using this.

I'm sure you don't need a response, but I'm going through and cleaning up my repos and would feel guilty just closing without a reply. Anyway, this error is coming from the selenium bindings, so I think the actual element on the page was no longer intractable. I don't know what the site looked like in 2018 so that's about all the help I can be.

FWIW I'll keep an eye out on this repo (surprisingly there are still people cloning this) in case anything pops up.
